### ISSUE TITLE
Absence of Neutroamine

### ISSUE THREAD

**Issue by anderschbe** [juanosarg/AlphaBees#7]
![image](https://user-images.githubusercontent.com/26141445/73087546-f43e4f80-3ed2-11ea-9ee2-0a7891fd7412.png)
![image](https://user-images.githubusercontent.com/26141445/73087640-1d5ee000-3ed3-11ea-893a-9ecba5ad3d6e.png)

**Comment by juanosarg** [comment]
That's glitched :) Neither plastic nor allow bees should ask for neutroamine
